name: Publish Docker image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'get tag version'
        required: true
        default: '0.0.1'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          VERSION=${{ github.event.inputs.tag }}
          if [ -z "$VERSION" ]
          then
            echo "from push"
            VERSION=${GITHUB_REF#refs/*/}
          else
            echo "workflow_dispatch"
          fi

          echo ::set-output name=version::${VERSION}

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: hoyawolf_frontend/hoyawolf_frontend
          tags: ${{ steps.prep.outputs.version }}, latest
          registry: docker.pkg.github.com
          dockerfile: Dockerfile_prod
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
